apiVersion: platform.platform.io/v1alpha1
kind: ResourceSummary
metadata:
  labels:
    app.kubernetes.io/name: platform-manager
    app.kubernetes.io/managed-by: kustomize
  name: resourcesummary-sample
spec:
  # TODO(user): Add fields here
